blank_issues_enabled: false
contact_links:
  - name: Pregunta general
    url: https://github.com/vicentegm2/angular-micro-portfolio/discussions
    about: Usa Discussions para dudas y soporte general