name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          check-latest: true
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Build (prod) with base-href
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | awk -F/ '{print $2}')
          npm run build -- --configuration production --base-href "/$REPO_NAME/"
          # Detect dist dir (Angular 22 output often under dist/<app>/browser)
          INDEX_HTML=$(find dist -type f -name index.html | head -n 1)
          if [ -z "$INDEX_HTML" ]; then
            echo "index.html not found under dist"
            ls -R dist || true
            exit 1
          fi
          DIST_DIR=$(dirname "$INDEX_HTML")
          echo "DIST_DIR=$DIST_DIR" >> $GITHUB_ENV
          echo "Using DIST_DIR: $DIST_DIR"

      - name: Debug dist tree
        run: |
          echo "Listing dist tree:"
          ls -R dist || true
          echo "DIST_DIR from env: $DIST_DIR"
          echo "Index exists?"; [ -f "$DIST_DIR/index.html" ] && echo "yes" || echo "no"

      - name: SPA fallback (copy index.html to 404.html)
        run: |
          cp "$DIST_DIR/index.html" "$DIST_DIR/404.html"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.DIST_DIR }}

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4